name: Miguel Ferreira dos santos neto

Formação:  Data Scientist  e Psicologia.

skills: Python, Power BI,  R program,  Metodologia de dados , Extração e tratamento de dados. Excel.


Projetos:

1 - Conferir portfólio 

